version: '3'

services:
  web:
    image: piotrzaborowski/frostplus:2.0.5pt
    environment:
      - serviceRootUrl=http://defs-dev.opengis.net:8082/FROST-Server
      - plugins.multiDatastream.enable=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=*U&Y6t5r
      - persistence_autoUpdateDatabase=true
    ports:
      - 8082:8080
      - 1885:1883
    depends_on:
      - database

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=*U&Y6t5r
    volumes:
      - postgis_volume:/var/lib/postgresql/data
    ports:
      - 5434:5432
volumes:
    postgis_volume: